version: '3'
services:
    web:
        build: ./front-end
        stdin_open: true
        tty: true
        ports: 
            - "8080:80"
        volumes:
            - "/app/node_modules" 
            - ".:/app"